export { HiMagnifyingGlass as SearchIcon } from 'react-icons/hi2';
export { HiXMark as CloseIcon } from 'react-icons/hi2';
export { HiShoppingCart as ShoppingCartIcon } from 'react-icons/hi2';
export { HiChevronDown as ChevronDownIcon } from 'react-icons/hi2';
export { HiChevronUp as ChevronUpIcon } from 'react-icons/hi2';
export { HiChevronLeft as ChevronLeftIcon} from "react-icons/hi2";
export { HiChevronRight as ChevronRightIcon } from 'react-icons/hi2';
export { HiMinusSmall as CheckboxIndeterminateIcon } from 'react-icons/hi2';
export { HiCheck as CheckIcon } from 'react-icons/hi2';
export { HiCalendarDays as CalendarIcon} from "react-icons/hi2";
export { HiOutlineMinus as MinusIcon } from 'react-icons/hi2';
export { HiOutlinePlus as PlusIcon } from 'react-icons/hi2';
export { HiOutlineClipboardDocument as ClipboardIcon } from 'react-icons/hi2';
export { HiOutlineClipboardDocumentCheck as ClipboardCheckIcon} from "react-icons/hi2";
export { HiHeart as HeartIcon } from 'react-icons/hi2';
export { HiEye as ShowPasswordIcon } from 'react-icons/hi2';
export { HiEyeSlash as HidePasswordIcon } from 'react-icons/hi2';
export { HiBars3 as MenuIcon } from 'react-icons/hi2';
export { HiOutlineMoon as ModeDarkIcon } from 'react-icons/hi2';
export { HiOutlineSun as ModeLightIcon } from 'react-icons/hi2';
export { HiOutlineComputerDesktop as ModeSystemIcon } from 'react-icons/hi2';
export { HiOutlineChatBubbleLeft as SpeechIcon } from 'react-icons/hi2';
export { HiOutlineHandThumbUp as ThumbsUpIcon } from 'react-icons/hi2';

export { FaGithub as GithubIcon} from "react-icons/fa";
